### ISSUE TITLE
[P1][providers] Ship Kimi and GLM/Z.AI built-in profiles for coding plans and PAYG APIs

### ISSUE THREAD

**Issue by aa22396584** [aa22396584/medley#115]
> **Migrated from ImL1s/medley#189**
> Originally created: 2026-08-06T16:22:14Z

## Parent

#186 — built-in access profiles and provider packs.

Blocked by:

- #187 typed access profiles and route identity;
- #188 source-pinned preset registry and catalog normalization.

## Goal

Ship production-shaped built-in access profiles for Kimi and GLM/Z.AI/BigModel without adding vendor-specific sampler forks or conflating subscription-plan keys with PAYG keys.

The first release must cover:

```text
Kimi Code subscription — OpenAI-compatible
Kimi Code subscription — Anthropic Messages-compatible
Kimi Open Platform PAYG
Z.AI GLM Coding Plan — OpenAI Chat Completions
Z.AI GLM Coding Plan — Anthropic Messages
Z.AI general PAYG API
BigModel China variants only after exact official endpoint/source pin
```

## Official source pins

Retrieved 2026-08-07 Asia/Taipei:

### Kimi

- Kimi Code overview, endpoints, models, third-party integration, and client identity warning: https://www.kimi.com/code/docs/en/
- Kimi Code/Open Platform/Membership key and billing separation: https://www.kimi.com/help/kimi-api/api-troubleshooting
- Kimi Code error reference and endpoint distinction: https://www.kimi.com/code/docs/en/kimi-code/error-reference.html

Confirmed product boundaries:

```text
Kimi Code subscription:
  OpenAI base:    https://api.kimi.com/coding/v1
  Messages base:  https://api.kimi.com/coding/
  credential:     Kimi Code plan API key
  billing:        subscription quota / optional Kimi Code top-up behavior
  intended use:   coding tools and developer workflows

Kimi Open Platform:
  base:           https://api.moonshot.cn/v1
  credential:     Open Platform API key
  billing:        pay as you go
  intended use:   general API/product integration
```

Kimi explicitly states these products' keys and balances are not interchangeable. Kimi also requires third-party tools to preserve their real client identity; Medley must not impersonate another client through User-Agent or originator metadata.

### GLM / Z.AI

- Z.AI API introduction and endpoint split: https://docs.z.ai/api-reference/introduction
- Z.AI HTTP guide: https://docs.z.ai/guides/develop/http/introduction
- Coding Plan tool endpoints: https://docs.z.ai/devpack/tool/others

Confirmed global endpoints:

```text
Z.AI general PAYG:
  https://api.z.ai/api/paas/v4

GLM Coding Plan OpenAI-compatible:
  https://api.z.ai/api/coding/paas/v4

GLM Coding Plan Anthropic-compatible:
  https://api.z.ai/api/anthropic
```

Z.AI documents the Coding endpoint as a coding/supported-tool endpoint and recommends the general endpoint for other scenarios. Wrong endpoint configuration does not consume the intended Coding Plan quota.

BigModel China endpoints and product rules must be source-pinned independently before being enabled; do not derive them from Z.AI hostnames.

### Kimi

```text
kimi/code-subscription/openai
  CredentialClass: SubscriptionPlanKey
  BillingClass: SubscriptionQuota
  UsageScope: InteractiveCoding
  Backend: ChatCompletions
  Auth: Bearer
  ClientIdentityPolicy: MedleyTruthful + provider-required identity

kimi/code-subscription/messages
  same product identity
  Backend: Messages

kimi/open-platform-payg/openai
  CredentialClass: PaygApiKey
  BillingClass: PayAsYouGo
  UsageScope: GeneralInference
  Backend: ChatCompletions
```

Do not model Kimi Code third-party API access as OAuth. The Kimi Code CLI `/login` device flow is a delegated-runtime possibility and a separate future issue; this provider pack uses the documented plan API key.

### GLM / Z.AI

```text
zai/coding-plan/openai
  CredentialClass: SubscriptionPlanKey
  BillingClass: SubscriptionQuota
  UsageScope: SupportedToolsOnly or InteractiveCoding
  Backend: ChatCompletions

zai/coding-plan/messages
  same product identity
  Backend: Messages

zai/general-payg/openai
  CredentialClass: PaygApiKey
  BillingClass: PayAsYouGo
  UsageScope: GeneralInference
  Backend: ChatCompletions
```

If JWT-token generation is exposed as an advanced Z.AI auth helper, it must remain provider-scoped, secret-safe, and optional. The built-in default should be direct API-key Bearer auth because that is the simplest documented path.

## Preset configuration UX

Examples after #16 consumes the registry:

```toml
[model_providers.kimi-code]
preset = "kimi"
access_profile = "code-subscription-openai"
env_key = "KIMI_CODE_API_KEY"

[model_providers.kimi-payg]
preset = "kimi"
access_profile = "open-platform-payg-openai"
env_key = "MOONSHOT_API_KEY"

[model_providers.glm-coding]
preset = "zai"
access_profile = "coding-plan-openai"
env_key = "ZAI_CODING_API_KEY"

[model_providers.glm-payg]
preset = "zai"
access_profile = "general-payg-openai"
env_key = "ZAI_API_KEY"
```

The wizard must show the product/access choice before asking for the env-var name. It must display that Coding Plan and PAYG are separately billed and cannot share a route implicitly.

### Kimi Code

- seed source-pinned candidates from the official Kimi Code model table;
- preserve model IDs exactly;
- record membership-tier facts as documentation facts, not account entitlement proof;
- if a supported account-scoped catalog exists, add it only after a separate exact protocol source pin;
- no automatic probing of every model;
- model additions/removals require source refresh or explicit live catalog evidence.

### Kimi Open Platform

- use an official model endpoint when supported and qualified;
- otherwise ship only documented candidates;
- keep Open Platform catalog separate from Kimi Code catalog even for the same underlying model family.

### GLM/Z.AI

- keep Coding Plan and PAYG catalogs separate;
- use exact source-pinned model IDs;
- do not assume a PAYG-visible model is covered by Coding Plan;
- do not infer future GLM version compatibility from a prefix;
- BigModel China catalog is a distinct profile, not a region toggle on a global credential.

## Client identity

Medley must send its truthful identity. Requirements:

- no OpenCode/Claude Code/Codex User-Agent impersonation;
- no copied originator/provider headers unless Medley is explicitly authorized to use them;
- profile-specific mandatory headers must be source-pinned and non-secret;
- doctor reports the configured identity policy without printing credential values;
- a provider rejection based on unsupported client identity is a distinct qualification result, not an invitation to spoof another client.

## Role and usage-scope enforcement

Medley is an interactive coding agent, so Coding Plan routes are plausible for the main agent path. They must not automatically be reused for every auxiliary/background path.

Before enabling a plan profile for each path, qualify:

```text
main interactive agent
headless one-shot prompt
subagent
summary/compaction
web-search auxiliary model
image-description model
background automation or scheduled task
```

If provider documentation permits only supported coding tools, conservative defaults are:

- main interactive agent: eligible after conformance;
- subagent: eligible only when it remains part of the interactive coding session and is documented/tested;
- background automation/application backend: ineligible;
- generic non-coding auxiliary workload: ineligible until explicitly qualified.

PAYG profiles may be used more broadly when capabilities and user policy allow.

## Endpoint/key pairing

The profile owns the endpoint class. Prevent these mistakes before network I/O:

```text
Kimi Code key + Open Platform endpoint
Kimi Open Platform key + Coding endpoint
GLM Coding Plan key + general endpoint
Z.AI PAYG key + Coding Plan endpoint unless explicitly selected
cross-region BigModel/Z.AI endpoint-key mismatch
```

Do not infer key class from an arbitrary prefix in generic config. A named profile may perform bounded profile-specific validation and provide an actionable warning, but the key value itself is never logged.

## Conformance requirements

Use Medley's existing backends, but qualify exact profiles:

### Chat Completions

- request path and model field;
- streaming chunk framing;
- tool calls and argument deltas;
- reasoning-effort fields only where supported;
- usage and cache metadata;
- error/rate-limit mapping;
- cancellation and retry boundaries.

### Messages

- endpoint/path joining;
- `x-api-key` versus Bearer requirements as documented by the profile;
- Anthropic version/header requirements if any;
- content block and tool-call streaming;
- thinking/reasoning fields;
- usage metadata;
- no Chat-specific assumptions.

A profile failing conformance remains fixture-compatible/experimental, not publicly supported.

## Doctor and readiness

Extend #15/#133 with typed results:

```text
wrong_product_endpoint
plan_key_missing
payg_key_missing
membership_or_plan_unavailable
model_not_in_plan
client_identity_rejected
scope_ineligible
protocol_mismatch
rate_limited
credential_ready_but_unqualified
```

A `402` or equivalent membership-benefit error is not a generic auth failure. It must not trigger PAYG fallback automatically.

## Usage and fallback

Coordinate with #18/#23:

- Kimi Code usage is subscription quota, not Open Platform API cost;
- GLM Coding Plan usage is plan quota, not Z.AI PAYG usage;
- plan limit/membership failure cannot silently switch to PAYG;
- same-lane fallback is allowed only among explicitly configured plan-covered models and only when exact-model mode is false;
- every fallback records requested/effective route and billing class;
- provider top-up/credits behavior is provider-owned and reported only when the provider exposes authoritative usage metadata.

## Mandatory fake/fixture tests

1. Each access profile expands to the exact source-pinned origin/backend/auth scheme.
2. Plan and PAYG profiles have distinct connection/access/billing identity.
3. Same model slug under plan and PAYG remains two routes.
4. Metadata-only model overrides preserve profile ownership.
5. Endpoint/credential override detaches to custom profile.
6. Missing plan key is unready with the correct env-var remediation.
7. Kimi Code key is never sent to `api.moonshot.cn`; Open Platform key is never sent to `api.kimi.com/coding` in a preset route.
8. GLM Coding Plan key is never sent to the general Z.AI endpoint in a preset route.
9. No Kimi/GLM credential or account marker appears in Debug, inspect, error, catalog, session, or fixture output.
10. Client identity is Medley, not another coding product.
11. Chat and Messages request/stream fixtures pass independently.
12. Malformed SSE/content blocks/usage/error responses fail safely.
13. 401/402/403/404/429/5xx remain distinct.
14. Subscription failure does not select a PAYG route.
15. Background/auxiliary paths reject plan profiles unless explicitly eligible.
16. Source retrieval date and normalized profile hash are deterministic.

## Live qualification

Live tests are opt-in and use user-provided authorized accounts only. For each profile:

- list or select at least one candidate model;
- run one bounded non-destructive coding turn;
- prove tool-call/stream compatibility;
- record requested/effective model when available;
- observe auth, plan/PAYG, and rate-limit failure classes without intentionally exhausting quota;
- verify no cross-product fallback or unexpected billing route;
- emit a sanitized immutable qualification report.

Disposition per access profile:

```text
QUALIFIED
LIMITED
MORE_DATA
REJECTED
NOT_RUN
```

## Relationships

- Parent: #186
- Blocked by: #187, #188
- Extends: #15, #16, #17, #18, #19, #23, #25, #31, #110, #133
- Does not implement Kimi CLI delegated login/ACP

## Non-goals

- Kimi web-session scraping or OAuth token reuse
- BigModel China support without exact official sources
- Model quality benchmarking
- Automatic account-tier detection from an email or model name
- Automatic plan-to-PAYG fallback
- Client identity spoofing
- General application-backend support for coding-only profiles

## Acceptance criteria

- [ ] Kimi Code and Kimi Open Platform are distinct built-in access profiles.
- [ ] GLM Coding Plan and Z.AI PAYG are distinct built-in access profiles.
- [ ] OpenAI and Messages variants reuse existing Medley backends with profile-specific conformance.
- [ ] Endpoint/key, billing, catalog, usage, and fallback separation is enforced.
- [ ] Client identity remains truthful.
- [ ] Plan profiles are restricted to qualified coding paths.
- [ ] Fake/fixture tests and source-pin checks pass.
- [ ] Public support claims are made per profile only after live or explicitly accepted limited qualification.
